### ISSUE TITLE
Add support for Gateway-API

### ISSUE THREAD

**Issue by qjoly** [toboshii/hajimari#163]
**Describe the solution you'd like**
> Gateway API is an open source project managed by the [SIG-NETWORK](https://github.com/kubernetes/community/tree/master/sig-network) community. It is an API (collection of resources) that model service networking in Kubernetes. These resources - [GatewayClass](https://gateway-api.sigs.k8s.io/api-types/gatewayclass), [Gateway](https://gateway-api.sigs.k8s.io/api-types/gateway), [HTTPRoute](https://gateway-api.sigs.k8s.io/api-types/httproute), [TCPRoute](https://gateway-api.sigs.k8s.io/concepts/api-overview/#tcproute-and-udproute), etc., as well as the Kubernetes [Service](https://kubernetes.io/docs/concepts/services-networking/service/) resource - aim to evolve Kubernetes service networking through expressive, extensible, and role-oriented interfaces that are implemented by many vendors and have broad industry support.

I mainly use API-Gateway (mostly because they are roles-based) and I think Hajimari support would be great. The annotations would be placed on the "HTTPRoute" resource (which works in a similar way to ingress). 

[Official documentation](https://gateway-api.sigs.k8s.io/)

**Additional context**
Example of HTTPRoute: 
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: example-route
  annotations:
    hajimari.io/enable = "true"
    hajimari.io/url = "example.com"
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "example.com"
  rules:
  - backendRefs:
    - name: example-svc
      port: 80
```
