### ISSUE TITLE
Hajimari dont find ingress or dont store config

### ISSUE THREAD

**Issue by JuezFenix** [toboshii/hajimari#42]
**Describe the bug**
Hajimari dont find ingress or dont store config (or maybe delete defaultEnable in config file)

**To Reproduce**

`apiVersion: apps/v1
kind: Deployment
metadata:
  name: hajimari
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: hajimari
      app.kubernetes.io/name: hajimari
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: hajimari
        app.kubernetes.io/name: hajimari
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: hajimari-config
      containers:
        - name: hajimari
          image: ghcr.io/toboshii/hajimari:latest
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: TZ
              value: UTC
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /config
          livenessProbe:
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 30
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: hajimari
      serviceAccount: hajimari
  strategy:
    type: Recreate`

`apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem`

`apiVersion: v1
kind: Service
metadata:
  name: hajimari
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http
  selector:
    app.kubernetes.io/instance: hajimari
    app.kubernetes.io/name: hajimari
  type: ClusterIP`

`customApps: []
defaultEnable: true
groups: []`

**Expected behavior**
Hajimari discover ingress on kubernetes cluster

**Additional context**
RBAC are deployed.

**Comment by toboshii** [comment]
It looks like you're missing a `namespaceSelector`? This is required to control which namespaces are monitored.

**Comment by JuezFenix** [comment]
Whatever change i do in config It's dont stored

**Comment by lapwat** [comment]
I have the same problem, I cannot make ingress auto-discovery work. My dashboard is empty.

![Screenshot_2023-07-19-15-11-28_1920x1080](https://github.com/toboshii/hajimari/assets/7073651/8dcf4bdd-eca1-4313-8e1e-1b5d12c69a50)


Here is the Flux Helm Release I use. I am expecting Hajimari to detect it's own ingress and show it with a Plex icon in the dashboard.

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: flux-system
spec:
  chart:
    spec:
      chart: hajimari
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: hajimari
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: hajimari
  values:
    defaultEnable: true
    ingress:
      main:
        annotations:
          hajimari.io/icon: plex
        enabled: true
        hosts:
        - host: start.exemple.com
          paths:
          - path: /
            pathType: Prefix
        ingressClassName: nginx
        tls:
        - hosts:
          - start.exemple.com
    namespaceSelector:
      matchNames:
      - hajimari
```

**Comment by lachnerd** [comment]
mine is also empty, added Namespaceselectors, added annotations, enabled "defaultEnable" but nothing shows up

**Comment by XenonPK** [comment]
Hello,

FYI, I fixed this by enabling persistence in the helm chart's values.yaml:
```
        # This requires persistence in order to discover the applications
        # https://github.com/toboshii/hajimari/issues/42
        persistence:
          data:
            enabled: true
            size: 128Mi
```
