### ISSUE TITLE
Bookmarks don't work

### ISSUE THREAD

**Issue by jvalskis** [toboshii/hajimari#68]
Trying to migrate groups to bookmarks, but can't get them to render. Documentation is a bit unclear, but in the sample `values.yaml` I found the `bookmarks` element, so I tried the following:

```yaml
  bookmarks:
    - group: Test
      bookmarks:
        - name: sample
          url: "https://sample.url"
```

However this did not work. The page rendered the following:

>### Bookmarks
>No bookmarks here...yet

Note that I also tried `globalBookmarks` and these worked when `showGlobalBookmarks` is set to true.
